### ISSUE TITLE
大佬 SSRPanel怎么限制单用户的速度啊 或者有什么好的方法 不限制太滥用了。

### ISSUE THREAD

**Issue by Goog686ii** [Chennhaoo/SSRR-Bash#1]
大佬 SSRPanel怎么限制单用户的速度啊 或者有什么好的方法 不限制太滥用了。

**Comment by Chennhaoo** [comment]
这个在胖虎的issues中有提到，你自己搜索一下。

**Comment by Goog686ii** [comment]
都是说的全局  怎么限制单用户的速度啊

**Comment by Chennhaoo** [comment]
限速只能同一个节点大家同一个限速，你是500K/S，我也是，他也是

**Comment by Goog686ii** [comment]
没法单端口限速吗？您说的那个加入标签那个 可以实现单端口限速吗

**Comment by Chennhaoo** [comment]
你要实现你限500K，我限600K？

**Comment by Goog686ii** [comment]
嗯 这个可以吗 ？我记得您在issues中有提到过说加入标签

**Comment by Chennhaoo** [comment]
这个不可以实现，我在issues中应该没提到过加入标签

**Comment by Goog686ii** [comment]
好吧 谢谢 大佬 网盘目前在用您的这个SSR-Panel后端版

**Comment by Chennhaoo** [comment]
你设置一个用户单线程限速或者总限速2M啊什么的

**Comment by Goog686ii** [comment]
好吧，

**Comment by Chennhaoo** [comment]
我这个脚本要是出现在网上了，那我就要删了项目了，低调哈，你自己用没啥的，不要给我宣传

**Comment by Goog686ii** [comment]
好的 放心吧 大佬 我不会分享出去的 这个确实真好用。
